name: flutter_country_picker
description: A new flutter plugin project.
version: 0.0.1
# homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms: 
      android: 
        package: com.example.flutter_country_picker
        pluginClass: FlutterCountryPickerPlugin
      ios: 
        pluginClass: FlutterCountryPickerPlugin
  assets:
    - assets/flags/